In [1]:
import os

In [2]:
%cd ..

from mtl.mv_eval import prepare_data,setup,create_dataloader,process_gallery,load_models

/data01/zhangleiting/_codes/fast-reid


In [3]:
config_file='configs/WildSplit1/mgn_R50-ibn.yml'
opt=['MODEL.WEIGHTS', 'logs/wildsplit1/mgn_R50-ibn/model_best.pth', 'MODEL.DEVICE', '\"cuda:1\"']
cfg=setup(config_file,opt)

In [4]:
models=load_models('wild')

[07/12 16:28:49 fastreid.engine.defaults]: Model:
MGN(
  (backbone): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (4): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): IBN(
          (IN): InstanceNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (BN): BatchNorm(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): Batch

In [5]:
data=prepare_data(root='datasets')

In [6]:
len(models[0])

7

In [7]:
data.num_gallery_images

{'1': 3829, '2': 3264, '3': 2533, '4': 610, '5': 1655, '6': 3710, '7': 1641}

In [8]:
query_dataloader,gallery_dataloader_dict=create_dataloader(data.query,data.gallery,cfg=cfg,root='datasets/Wildtrack_eval')

/data01/zhangleiting/anaconda3/envs/fast/lib/python3.8/site-packages/torchvision/transforms/transforms.py:332: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(


In [8]:
for batch in query_dataloader:
    query=batch
    break

In [9]:
query[0][3]

tensor([1])

In [8]:
for idx,batch in enumerate(gallery_dataloader_dict[1]):
    gallery=batch
    break

In [9]:
len(gallery)

4

In [9]:
res=process_gallery(model_dict=models[0],gallery_dataloader_dict=gallery_dataloader_dict)

/data01/zhangleiting/anaconda3/envs/fast/lib/python3.8/site-packages/torch/nn/functional.py:780: UserWarning: Note that order of the arguments: ceil_mode and return_indices will changeto match the args list in nn.MaxPool2d in a future release.
  warnings.warn("Note that order of the arguments: ceil_mode and return_indices will change"


feature shape:torch.Size([32, 2048])


In [13]:
res

tensor([[ 0.5947, -0.0880,  0.5249,  ...,  0.1499, -0.6629,  0.7057],
        [ 0.8657, -0.2813,  1.1362,  ..., -0.0277, -0.8491,  0.4108],
        [ 0.3091, -0.3884,  1.4874,  ..., -0.6052, -1.3945,  0.3211],
        ...,
        [-0.0364,  0.1754,  1.0748,  ...,  0.3376,  0.2779,  0.0426],
        [-0.3530,  0.0113, -1.1658,  ..., -0.3644, -0.4592, -0.5700],
        [ 1.0838,  0.5502,  1.3705,  ...,  0.4839, -0.4363,  0.2060]],
       device='cuda:1', grad_fn=<CatBackward0>)

In [11]:
len(query_dataloader)

850

In [10]:
len(gallery_dataloader_dict[1])

120

In [12]:
32*119

3808

In [19]:
data.query_ids

{0: 0,
 1: 1,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 8: 8,
 10: 10,
 12: 12,
 13: 13,
 14: 14,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 22,
 23: 23,
 30: 30,
 33: 33,
 35: 35,
 36: 36,
 37: 37,
 38: 38,
 40: 40,
 41: 41,
 43: 43,
 46: 46,
 47: 47,
 48: 48,
 49: 49,
 51: 51,
 54: 54,
 55: 55,
 56: 56,
 59: 59,
 60: 60,
 61: 61,
 62: 62,
 63: 63,
 64: 64,
 65: 65,
 66: 66,
 67: 67,
 69: 69,
 70: 70,
 72: 72,
 73: 73,
 74: 74,
 75: 75,
 77: 77,
 78: 78,
 79: 79,
 80: 80,
 81: 81,
 82: 82,
 83: 83,
 84: 84,
 85: 85,
 86: 86,
 87: 87,
 89: 89,
 91: 91,
 92: 92,
 93: 93,
 94: 94,
 115: 115,
 116: 116,
 121: 121,
 122: 122,
 124: 124,
 125: 125,
 131: 131,
 134: 134,
 135: 135,
 136: 136,
 139: 139,
 144: 144,
 145: 145,
 147: 147,
 149: 149,
 152: 152,
 158: 158,
 160: 160,
 161: 161,
 162: 162,
 163: 163,
 166: 166,
 168: 168,
 170: 170,
 172: 172,
 174: 174,
 177: 177,
 181: 181,
 186: 186,
 187: 187,
 189: 189,
 190: 190,
 193: 193,
 196: 196,
 198: 198,
 210: 210,
 218: 218,
 224: 224,
 2

In [15]:
from glob import glob
sub_dirs = sorted(glob(os.path.join(path, '*')))

In [16]:
sub_dirs

['datasets/Wildtrack_eval/gallery/1',
 'datasets/Wildtrack_eval/gallery/2',
 'datasets/Wildtrack_eval/gallery/3',
 'datasets/Wildtrack_eval/gallery/4',
 'datasets/Wildtrack_eval/gallery/5',
 'datasets/Wildtrack_eval/gallery/6',
 'datasets/Wildtrack_eval/gallery/7']

In [ ]:
sorted(osp.path)

In [2]:
import torch

In [3]:
ta=torch.Tensor(2,4)
tb=torch.Tensor(3,4)
tc=torch.Tensor(11,4)
ta=ta.to('cuda:1')
tb=tb.to('cuda:1')
tc=tc.to('cuda:1')


In [4]:
ta

tensor([[-1.0193e+06,  4.5633e-41, -1.0193e+06,  4.5633e-41],
        [ 4.4842e-44,  0.0000e+00,  8.9683e-44,  0.0000e+00]], device='cuda:1')

In [13]:
int(ta[0][0])

-1019335

In [6]:
test=torch.Tensor([1])

In [11]:
int(test[0])

1

In [28]:
ttotal=torch.cat([ta,tb,tc])

In [29]:
ttotal.shape

torch.Size([16, 4])

In [30]:
ttotal.device

device(type='cuda', index=1)

: 

In [2]:
import numpy as np

In [7]:
a=np.array([[1,2,3],[1.5,2.9,2.8],[0.9,1.1,2]])

In [14]:
indices=a.argsort(axis=1)

In [10]:
a[0].argsort()

array([0, 1, 2])

In [15]:
matches = (a[indices] == 2).astype(np.int32)

In [16]:
matches

array([[[0, 1, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 1, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 0, 0],
        [0, 0, 1]]], dtype=int32)

In [13]:
a

array([[1. , 2. , 3. ],
       [1.5, 2.9, 2.8],
       [0.9, 1.1, 2. ]])

In [19]:
b=np.array([1,3,4,5,2,8])
indice=b.argsort()

In [20]:
b[indice]

array([1, 2, 3, 4, 5, 8])